-- Create Featured Status Enum
CREATE TYPE featured_status AS ENUM ('pending', 'active', 'expired', 'rejected');

-- Create Featured Queue Table
CREATE TABLE featured_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id UUID REFERENCES listings(id) NOT NULL,
  location TEXT NOT NULL, -- Copied from listing to lock it in
  status featured_status DEFAULT 'pending' NOT NULL,
  requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE,
  ends_at TIMESTAMP WITH TIME ZONE
);

-- Index for FIFO retrieval and slot counting
CREATE INDEX idx_featured_location_status ON featured_queue(location, status);
CREATE INDEX idx_featured_requested_at ON featured_queue(requested_at);

-- Enable RLS
ALTER TABLE featured_queue ENABLE ROW LEVEL SECURITY;

-- Initial Policies
CREATE POLICY "Public read access for active featured items" ON featured_queue
  FOR SELECT USING (status = 'active');
