-- Create custom enum for user roles
CREATE TYPE app_role AS ENUM ('visitor', 'creator', 'operator');

-- Create Business Categories table
CREATE TABLE business_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Product Categories table
CREATE TABLE product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on categories (Public Read-Only)
ALTER TABLE business_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access for business_categories" ON business_categories
  FOR SELECT USING (true);

CREATE POLICY "Public read access for product_categories" ON product_categories
  FOR SELECT USING (true);
