-- Migration: Add Tier to Listings (for Subscription Autopilot)
-- Generated by Antigravity

ALTER TABLE public.listings 
ADD COLUMN IF NOT EXISTS tier text DEFAULT 'Basic'::text;

-- Update existing rows to Basic if null
UPDATE public.listings SET tier = 'Basic' WHERE tier IS NULL;

-- Index for filtering by tier (e.g. for showcasing Pro users)
CREATE INDEX IF NOT EXISTS listings_tier_idx ON public.listings (tier);
