-- Create custom enum for user roles
CREATE TYPE app_role AS ENUM ('visitor', 'creator', 'operator');

-- Create Business Categories table
CREATE TABLE business_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Business Categories (Exactly 16)
INSERT INTO business_categories (name) VALUES
  ('Photography'),
  ('Graphic Design'),
  ('Web Development'),
  ('Copywriting'),
  ('Marketing'),
  ('SEO'),
  ('Videography'),
  ('Illustration'),
  ('Branding'),
  ('Animation'),
  ('Social Media'),
  ('UX/UI Design'),
  ('Music & Audio'),
  ('3D Design'),
  ('Software Development'),
  ('Virtual Assistant');

-- Create Product Categories table
CREATE TABLE product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Product Categories (Initial Set)
INSERT INTO product_categories (name) VALUES
  ('Templates'),
  ('E-books'),
  ('Presets'),
  ('Courses'),
  ('Audio Packs'),
  ('3D Models'),
  ('Icons'),
  ('Fonts'),
  ('Stock Photos'),
  ('Software Tools');

-- Enable RLS on categories (Public Read-Only)
ALTER TABLE business_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access for business_categories" ON business_categories
  FOR SELECT USING (true);

CREATE POLICY "Public read access for product_categories" ON product_categories
  FOR SELECT USING (true);
